service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-3

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
